### ISSUE TITLE
snap breaks if /etc/get_iplayer/options exists

### ISSUE THREAD

**Issue by mattiaswerner** [snapcrafters/get-iplayer#4]
Like title says, if there is a file located at /etc/get_iplayer/options, the snap fails to run with the error

"ERROR: Cannot read options file: /etc/get_iplayer/options"

If changing from apt installation to snap, this is a showstopper for a regular user.

**Comment by popey** [comment]
Hm, I wonder if we can get system-files permission for that file as per https://forum.snapcraft.io/t/the-system-files-interface/9358

**Comment by popey** [comment]
I am having difficulty reproducing this. What are the permissions on the options file? What's its contents on your system? I have prepared a branch which can possibly fix the issue, but I can't reproduce it to see if it works or not.

**Comment by Nightmayr** [comment]
This issue exists again. I'm using the latest snap version 3.25 from the snap store on Ubuntu 20.04.
`ERROR: Cannot read options file: /etc/get_iplayer/options`
I did have the apt version installed from the ppa. I've noticed that the current snapcraft.yaml doesn't have the system-files interface to be able to read this file, is this intentional?
